<?php

namespace Goldnead\StatamicPayments\Tags;

use Goldnead\StatamicPayments\Legal\Links;
use Goldnead\StatamicPayments\Models\Payment;
use Goldnead\StatamicPayments\Support\Catalogue;
use Goldnead\StatamicPayments\Support\FollowUp;
use Statamic\Tags\Tags;

/**
 * The `payments` tag: the follow-up offer, and the two statutory links.
 *
 * {{ payments:offer payment="{payment}" product="begleit-cd" }} … {{ /payments:offer }}
 * {{ payments:withdrawal_url }}
 * {{ payments:cancellation_url }}
 *
 * **`offer`** yields nothing at all unless the offer may actually be made: the
 * site has switched follow-ups on, this payment is paid, and the buyer agreed to
 * be charged again. A page that showed the offer and then failed at the till
 * would be worse than a page that never showed it.
 *
 * The template still has to carry the order button, labelled unambiguously,
 * with the essential details directly above it. The tag hands over `action`,
 * `amount`, `currency` and `name` so those details can be printed; it will not
 * print the button, because a button generated by a package is exactly the
 * thing nobody reads before shipping. See `docs/follow-up-offers.md`.
 *
 * **`withdrawal_url`** and **`cancellation_url`** are the addresses of the
 * § 356a and § 312k buttons, for the footer. Empty where the respective flow is
 * switched off. The label is the site's to print — `withdrawal.button` and
 * `cancellation.button` in the translations carry the statutory wording.
 */
class Payments extends Tags
{
    protected static $handle = 'payments';

    public function offer(): array|string
    {
        $payment = $this->payment();
        $handle = (string) $this->params->get('product', '');
        $product = app(Catalogue::class)->find($handle);

        $followUp = app(FollowUp::class);

        if (! $payment || ! $product || ! $followUp->eligible($payment)) {
            return $this->parseNoResults();
        }

        // Already taken from this payment: the offer disappears rather than
        // inviting a second purchase of the same thing.
        if ($followUp->alreadyTaken($payment, $product['handle'])) {
            return $this->parseNoResults();
        }

        return $this->parse([
            'payment_id' => $payment->getKey(),
            'product' => $product['handle'],
            'name' => $product['name'],
            'amount' => number_format($product['amount_cent'] / 100, 2, ',', '.'),
            'amount_cent' => $product['amount_cent'],
            'currency' => $product['currency'],
            'action' => route('statamic-payments.offer.accept'),
        ]);
    }

    /** `{{ payments:withdrawal_url }}` — § 356a BGB. */
    public function withdrawalUrl(): string
    {
        return Links::withdrawal() ?? '';
    }

    /** `{{ payments:cancellation_url }}` — § 312k BGB, without login. */
    public function cancellationUrl(): string
    {
        return Links::cancellation() ?? '';
    }

    protected function payment(): ?Payment
    {
        $value = $this->params->get('payment');

        if ($value instanceof Payment) {
            return $value;
        }

        if (is_numeric($value)) {
            return Payment::find((int) $value);
        }

        return null;
    }
}
